### PR TITLE
Secular: Add Method 2, changed site to MojaveD173

### PR DESCRIPTION
**Pull request by EJFielding**
Added code to calculate Method 2, added site MojaveD173, and changed to use that for Secular validation

### CODE REVIEW

**Comment by EJFielding** [comment]
Note that I left the notebook file name the same as before to make it easier to compare to the previous version in ReviewNB.

**Comment by EJFielding** [comment]
<p>This was a leftover from Kang's notebook. No longer needed, so I deleted it.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/30/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>now removed</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/30/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by dbekaert — APPROVED** [review]
LGTM @EJFielding @sssangha were you able to run this with teh pre-staged data?

**Comment by yunjunz** [comment]
Could we drop `NISAR_SES_` from the notebook filename as well?

**Comment by EJFielding** [comment]
@yunjunz David asked me to keep the name the same so that the new version can be easily compared to the old version in ReviewNB.

**Comment by EJFielding** [comment]
Maybe someone can send another renaming PR after this is merged?

**Comment by dbekaert** [comment]
Can use the `git mv` command to rename it to a new name. I think that would still allows for comparision

**Comment by yunjunz** [comment]
If you recall our video meeting last time, together with Marco, you could also use `right click --> rename` within jupyter to do this, similar to `git mv`. Both will allow the comparison.

**Comment by EJFielding** [comment]
I renamed both the Coseismic and Secular notebooks.

**Comment by EJFielding** [comment]
The last commit by @nabolfat was some heading and table of contents updates for the Coseismic notebook.

**Review by dbekaert — APPROVED** [review]
LGTM

**Pull request merged**
