### PR TITLE
Include sample variogram analysis

### PR DESCRIPTION
**Pull request by cmarshak**
This includes python scikit workflow for variogram: https://github.com/nisar-solid/ATBD/issues/8

### CODE REVIEW

**Comment by dbekaert** [comment]
hi @cmarshak, this looks good, with an example in the jupyter.
Suggest to add the requirements in docs/requirements

@yunjunz, would be good to add some sort of install guidelines as well
We do we put that now in your installation repo?

**Comment by yunjunz** [comment]
For the requirements.txt file from this PR, it could be merged into the `ATBD/docs/requirements.txt` file. Then there should be no change needed in the `conda_envs` repo.

**Comment by yunjunz** [comment]
@dbekaert Unrelated to this PR, now it makes more sense to merge the `conda_envs` repo into the `ATBD` repo. It could be done via the following.
+ conda_envs/README.md --> ATBD/docs/installation.md
+ conda_envs/insar/config.rc --> ATBD/docs/config.rc

Then we don't need the conda_envs repo anymore, and everything is within ATBD and simple. If you agree, I will go for this in another PR.

**Comment by dbekaert** [comment]
> @dbekaert Unrelated to this PR, now it makes more sense to merge the `conda_envs` repo into the `ATBD` repo. It could be done via the following.
> 
>     * conda_envs/README.md --> ATBD/docs/installation.md
> 
>     * conda_envs/insar/config.rc --> ATBD/docs/config.rc
> 
> 
> Then we don't need the conda_envs repo anymore, and everything is within ATBD and simple. If you agree, I will go for this in another PR.

agreed

**Review by yunjunz — APPROVED** [review]
LGTM, thank you @cmarshak.

**Pull request merged**
