### PR TITLE
Coseismic: modified to better use staged data

### PR DESCRIPTION
**Pull request by EJFielding**
Modified Coseismic notebook to reuse the MintPy configuration file included with staged data (same as was done in Secular notebook) so that MintPy will skip the network inversion that takes a long time on "nisar-calval" virtual machines

### CODE REVIEW

**Comment by EJFielding** [comment]
<p>The present version of the staged dataset for <code>RidgecrestA64</code> includes the configuration file named <code>Ridgecrest_Sen.txt</code>. I was trying to avoid recreating the staged data with the different configuration file name.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/33/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dbekaert** [comment]
I think this PR is now replaced with PR #35 @EJFielding @nabolfat ?

**Comment by nabolfat** [comment]
Yes, PR#35 is addressing the same issue. I added an if condition so it is recognized that the Ridgecrest config-file name is different from other staged data.

**Comment by dbekaert** [comment]
Per comment of @nabolfat, closing this here

**Pull request closed without merging**
