### PR TITLE
secular: refactor A.4 GNSS time-series plots 

### PR DESCRIPTION
**Pull request by yunjunz**
This PR includes the following changes:

For the 3 notebooks under `methods/`:
+ sort module import based on standard practice
+ ~~update mintpy imports usage to the latest dev version~~ [reverted]

For the `methods/secular/` only:
+ remove unused module imports
+ refactor the A.4 section:
   - simplify InSAR/GNSS reading by leveraging mintpy func
   - remove the un-meaningful velocity plot, which is extensively shown in the sections above
   - auto grab insar time-series filename based on template config.

### CODE REVIEW

**Comment by EJFielding** [comment]
@yunjunz When did you change MintPy to have the `mintpy.cli` module? I tried to run this on the `nisar-calval` version of OpenSARLab and it did not find that module.
The system there was updated last month to `MintPy version 1.4.1, date 2022-08-15`, which I think comes from conda-forge.

**Comment by yunjunz** [comment]
It was committed about a month ago, after the last release of 1.4.1. 

I plan to release version 1.5.0 in ~1 month to include this feature. I have completely migrated to the version with `mintpy.cli` sub-module, and it has been great.

**Comment by EJFielding** [comment]
Can we add some code to work with the 1.4.1 release that is installed on the OpenSARLab servers?

**Comment by yunjunz** [comment]
Considering that the ATBD development is mostly done, we should not need the development version of mintpy anymore. Thus, one simple way is to use the conda-installed version of mintpy, with a fixed version number, similar to what we have done for gdal. If so, I will revert some of the changes in this PR, to work with mintpy-1.4.1 only. What do you think?

**Comment by EJFielding** [comment]
Yes, I think it would be better to stick with the released version for the review. Does that mean that we also need to change the installation instructions?

**Comment by yunjunz** [comment]
Yes, a little bit. I will try to update the PR for this later tonight.

**Review by EJFielding — APPROVED** [review]

**Pull request merged**
