### PR TITLE
Create Coseismic_Requirement_Validation-Approach2.ipynb

### PR DESCRIPTION
**Pull request by EJFielding**
New version of Coseismic notebook with approach 1 and 2 code added, along with other changes.

### CODE REVIEW

**Comment by dbekaert** [comment]
@EJFielding Suggest not to change names of the notebook as then we loose the ability to track versions using github or compare with the notebook tool. If a name change is needed please use git mv capabilities.

**Comment by EJFielding** [comment]
@dbekaert OK, I removed the old version and moved the new version to the same name.

**Comment by dbekaert** [comment]
hi @EJFielding Were you running this from already existing run? I noticed some error messages in the mintpy output which seems not to have stopped from continue the running. The version is slightly different from what was used on OSL.

One plot i noticed for secular or mean velocity showed now some coseismic signal. 

Stats look good!

**Comment by dbekaert** [comment]
> @dbekaert OK, I removed the old version and moved the new version to the same name.

Worked well, thanks for doing that!

**Comment by EJFielding** [comment]
<p>Yes, because I used the staged data, the <code>ARIA-tools</code> files do not exist. The MintPy script tries to look for them to check if they changed and did not find them. I am not sure how to fix that. Maybe @yunjunz could suggest a way to avoid this?</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>Yes, the problem affects all the <code>smallbaselineApp.py</code> calls. </p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>This depends on whether the velocity fit was done with the coseismic step or not. If the coseismic step is not estimated, then the linear velocity absorbs the coseismic.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>The staged <code>velocity.h5</code> file was the fit with the linear velocity plus coseismic step function at time of Ridgecrest earthquake. </p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
<p>I just tried to copy over the printout custom template and tested on the San Francisco Bay example dataset, and could not re-produce the error. I can't think of causes on top of my head.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
<p>This means all the smallbaselineApp calls in this notebook are not actually run.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dbekaert** [comment]
@mgovorcin did you experience this on OSL?

**Comment by EJFielding** [comment]
<p>I think it is because we are using <code>mintpy.load.azAngleFile: ../azimuthAngle/\*.vrt</code> in the MintPy configuration file, but the SF Bay example uses a specific file name. Since we have been changing the intervals downloaded, it is much easier to use the <code>*.vrt</code> name instead of having to change the file name to whatever the new name is.  </p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>Does everybody else always modify their MintPy template file every time they run <code>ariaTSsetup.py</code> to match whatever new filename is created? </p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>I notice this trackback error before, and believe it is associated with staged ifgramStack.h5 and  "mintpy.network.excludeIfgIndex" flag. Initially, the stack is staged with excluded 6 ifgs, so when we change it to use all pairs, I guess MintPy cannot find them and raise the error. Should we leave it like this or staged the data again with all included pairs? </p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>I just reproduced the error. Believe it is associated with the update of smallbaseline config file as it is different than the staged one (having also different timestamp). So, guess MintPy is trying to reload the data but it cannot find ARIA stack folder and raise the error.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
<p>@mgovorcin could you show here how to re-produce the error? preferably on laptop for me to easily test.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>@yunjunz I got the same error on my Mac laptop. It happens when we download the staged data that does not include the ARIA-tools products and run the script a second time in the same directory.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>@yunjun try to run the notebook with these changes:</p><ol><li> in Prep A.: set sites['RidgecrestA64']['ifgExcludeList'] = 'no'</li><li> run cells Prep A, Prep B, 2.1. 'Set Up MintPy Configuration file', and then 2.2 'Load data into Mintpy'</li></ol>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>@yunjunz Looking at it again, it can also be due to MintPy parsing. It thinks that it needs to change the configuration because of the backslash that is added as an escape for the asterisk.</p><pre class="ql-syntax" spellcheck="false">mintpy.load.azAngleFile: ../azimuthAngle/\*.vrt --&gt; ../azimuthAngle/*.vrt
</pre>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
<p>Thank you @EJFielding and @mgovorin, I was able to re-produce the error. The issue is in the template updating code: the staged default template option "mintpy.network.excludeIfgIndex = [123,124,125]" has "[]" included, these are special characters for <code>re</code> expression syntax, causing issues during the searching and updating of template files. It's now fixed in https://github.com/insarlab/MintPy/pull/768. Thank you for founding this issue!</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EJFielding** [comment]
<p>Thanks, @yunjunz! I pulled the new version of MintPy to my Mac and run the notebook again, and it is working well without the errors. It is re-running the network inversion without the excluded scenes.</p>

---

 <a href='https://app.reviewnb.com/nisar-solid/ATBD/pull/26/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by dbekaert — APPROVED** [review]
Looks good with all the fixes made.

**Pull request merged**
