### PR TITLE
Added CalVal site info

### PR DESCRIPTION
**Pull request by EJFielding**
Added KMZ and Excel workbook with information about the CalVal sites.

### CODE REVIEW

**Comment by EJFielding** [comment]
@yunjunz could you do a quick review of this PR?

**Comment by yunjunz** [comment]
Thanks @EJFielding. I only have suggestions on the organization of the changes. Below would be my suggested structure:

```bash
/docs or /methods       # I am very against new root-level folders unless necessary, this one seems to belong to /docs or /methods
    /calval_sites              # use "snake_case" whenever it's applicable. Mixed cases are prone to typos.
        README.md         # a simple README would be good
        nisar_ses_calval_sites_v3.kmz
        nisar_ses_calval_sites_v3.xlsx        # maybe a `.csv` format would be more generic? I am not sure if this is import or not, please ignore this if it's not
```

**Comment by EJFielding** [comment]
Thanks for the suggestions @yunjunz. I moved and renamed the new directory. The Excel workbook has some text formatting that make it easier to read. That will be lost if we convert it to csv. The workbook is not really useful for other types of analysis anyway.

**Comment by yunjunz** [comment]
Thanks @EJFielding. The last detail: shall we rename the markdown file to `README.md`, then it will be shown by default when one browses to this page: https://github.com/EJFielding/ATBD/tree/CalVal/docs/cal_val_sites.

**Review by yunjunz — APPROVED** [review]
Looks all good to me!

**Pull request merged**
